CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'mthiry'@'%' IDENTIFIED BY '123456789';
GRANT ALL PRIVILEGES ON wordpress.* TO 'mthiry'@'%';

-- Creating root user
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root123456789';
FLUSH PRIVILEGES;